# Generated by Django 5.1.1 on 2024-09-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fit_level',
            field=models.FloatField(default=0, verbose_name='Соответствие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='skill',
            field=models.TextField(default='', verbose_name='Навыки'),
        ),
    ]
