# Generated by Django 5.1.1 on 2024-09-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplo', '0003_searchstring_alter_employee_fit_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=5, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='', max_length=5, verbose_name='Должность'),
        ),
    ]
