# Generated by Django 5.1.1 on 2024-09-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplo', '0004_alter_employee_name_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=5, verbose_name='Имя')),
                ('position', models.CharField(default='', max_length=5, verbose_name='Должность')),
                ('skill', models.TextField(default='', verbose_name='Навыки')),
                ('level', models.CharField(default='', max_length=5, verbose_name='Уровень')),
                ('fit_level', models.FloatField(default=0, verbose_name='Соответствие')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
